add
girleffect/ge-web pull request #11
Opened 2021-11-22 17:41 UTC by codiebeulaine

2021-11-29 11:12 UTC, zerolab requested changes
Hey @codiebeulaine,

This PR has lots of great changes. Left a number of comments, suggestions and questions.

2021-11-29 11:12 UTC, zerolab commented on profiles/views.py
> +            return HttpResponseForbidden()
question: why raise a 403 here, when the other views return an more specific error message?


I feel like this needs a bit of rework: we get to this view from https://github.com/girleffect/ge-web/pull/11/files#diff-24d82cf2552dbb8559c90d6d4f0481d348c26a9ab90ef850c18af2b87e5098b1R187-R190, the existence of the username/token kwargs should probably be checked in the view's `get` method and raise the necessary 403 there. This should also cater for the use case where the user directly goes to `/profiles/reset-password/`

2021-11-30 09:42 UTC, codiebeulaine commented on profiles/models.py
> +class SecurityQuestion(Page):
needed for translations

2021-11-30 10:04 UTC, zerolab commented on profiles/urls.py
> +from django.conf.urls import path
`from django.urls import path`

also, `path()` doesn't take a regex, so `path(r"^logout/$", ...)` -> `path("logout/", ...)`

2021-11-30 12:34 UTC, codiebeulaine commented on profiles/views.py
> +            return HttpResponseForbidden()
the django reset view was not used because our users most likely don't have email addresses

2021-11-30 16:00 UTC, zerolab requested changes
Much cleaner!
A few areas that could benefit from some docblocks, plus the password reset question

2021-12-01 08:53 UTC, codiebeulaine commented on profiles/models.py
> +class GEUser(models.Model):
👍

2021-12-01 08:54 UTC, codiebeulaine commented on profiles/templates/profiles/change_password.html
> +    {% if form.errors or form.non_field_errors %}
👍

2021-12-01 09:12 UTC, codiebeulaine commented on profiles/views.py
> +    def form_valid(self, form):
👍

2021-12-01 09:16 UTC, codiebeulaine commented on profiles/views.py
> +            user.set_password(password)
👍

2021-12-01 09:18 UTC, codiebeulaine commented on profiles/models.py
> +class SecurityQuestion(Page):
:+1:

2021-12-01 09:18 UTC, codiebeulaine commented on profiles/forms.py
> +)
👍

2021-12-01 09:36 UTC, codiebeulaine commented on profiles/views.py
> +            user.set_password(password)
persisting with token because request.user is anonymous at this point

2021-12-01 10:35 UTC, KaitCrawford commented on profiles/models.py
> +            raw_answer.strip().lower() if raw_answer else None, self.answer, setter
@codiebeulaine could you point me to some docs for how this works pls? the ones I'm looking at for check_password say it only takes two arguments but I see you're sending 3 here.

2021-12-01 10:55 UTC, KaitCrawford commented on profiles/views.py
> +                    "Sorry, but that is an invalid username. Please don't use your phone number or email address in your username."
I think it will be confusing and misleading to have the "don't use your phone number" text in this error message. since that's not what the problem is. Could we leave it out?

2021-12-01 11:45 UTC, KaitCrawford commented on profiles/templates/profiles/viewprofile.html
> +    <a href="{% url 'reset_password' %}" class="call-to-action__button call-to-action__button--primary">{% trans "Change my pin" %}</a>
I think  this is going to the wrong url. The `reset_password` url is the one that requires a token generated from the `forgot_password` form submission

2021-12-02 10:13 UTC, zerolab commented on profiles/models.py
> +            raw_answer.strip().lower() if raw_answer else None, self.answer, setter
https://github.com/django/django/blob/stable/3.1.x/django/contrib/auth/hashers.py#L30 (or on the [main branch](https://github.com/django/django/blob/32b7ffc2bbfd1ae055bdbe287f8598de731adce1/django/contrib/auth/hashers.py#L31))

if a setter is passed, and the password needs updating (e.g. hashing algorithm has changed), then that gets called.

Saying that, this should probably use `setter=setter`

2021-12-02 10:36 UTC, zerolab reviewed
There were a couple of points from @KaitCrawford that are worth tweaking + https://github.com/girleffect/ge-web/pull/11/files#r760945217

And no further comments from me. Nice work!

2021-12-06 12:47 UTC, codiebeulaine commented on profiles/views.py
> +                    "Sorry, but that is an invalid username. Please don't use your phone number or email address in your username."
👍

2021-12-06 12:54 UTC, merged