Add forms
girleffect/ge-web pull request #13
Opened 2021-11-24 18:31 UTC by codiebeulaine

2021-12-08 10:09 UTC, zerolab requested changes
Lots of good things here @codiebeulaine 

Left a number of comments and suggestions

2021-12-08 10:09 UTC, zerolab commented on forms/models.py
> +        results = dict()
considering the form page has a `show_results` boolean, this whole bit should be conditional.

I would do:

```python
if not self.show_results:
    # return early, without further processing
    return context

results = dict()
# ...
```

2021-12-08 10:09 UTC, zerolab commented on forms/templates/forms/form_page_landing.html
> +        <h2>Results</h2>
suggestion: wrap this in a `{% if results %}`

2021-12-08 10:09 UTC, zerolab commented on forms/tests.py
> +# Create your tests here.
would be good to have a test case for this:

1. for the logged in/active, or allow anonymous submissiont
2. show/don't show results
3. multi-step would be a nice addition

2021-12-08 10:09 UTC, zerolab commented on profiles/migrations/0002_auto_20211206_1945.py
> +# Generated by Django 3.1.13 on 2021-12-06 19:45
I can't see where this migration is coming from in the changes from this PR. 
Was this a missing migration from #11 or some other work in progress? Would be good to address it separately.

Additionally, I would recommend using named migrations. ie rename `profiles/migrations/0002_auto_20211206_1945.py` to `profiles/migrations/0002_terms_and_conditions_changes.py` or something more descriptive. It makes looking at the migrations more intuitive

2021-12-10 09:59 UTC, zerolab commented on forms/templates/forms/form_page.html
> +                    <button type="submit">{% trans "Submit" %}</button>
this needs `i18n` added to the `{% load ` line

2021-12-13 11:46 UTC, codiebeulaine commented on forms/templates/forms/form_page.html
> +                    <button type="submit">{% trans "Submit" %}</button>
👍

2021-12-13 11:47 UTC, codiebeulaine commented on profiles/migrations/0002_auto_20211206_1945.py
> +# Generated by Django 3.1.13 on 2021-12-06 19:45
👍

2021-12-13 11:49 UTC, codiebeulaine commented on forms/models.py
> +        results = dict()
👍

2021-12-13 12:02 UTC, zerolab commented on forms/templates/forms/form_page_landing.html
> +        {% if Results %}
```suggestion
        {% if results %}
```

2022-01-03 09:49 UTC, KaitCrawford commented
@zerolab :wave: I hope you had a relaxed festive season.
When you have a chance could you please review the changes that have been made to this PR and indicate if you are happy with them. I've added the requested tests in another PR (based off this branch) so that this one doesn't get out of hand since I'm having some trouble with them. https://github.com/girleffect/ge-web/pull/32

2022-01-04 11:34 UTC, zerolab approved these changes
Hey @KaitCrawford @codiebeulain, happy New Year!

This LGTM now. 

Was initially not so sure about the output on the homepage, but looking at the template that looks like it is WIP, so no more worries.

2022-01-04 13:00 UTC, KaitCrawford commented
@zerolab thanks! Yeah, the templates are WIP. We're meeting with Mitso tomorrow to check in and I'll merge this PR after I've confirmed that she's happy with that process

2022-01-05 14:07 UTC, merged